### PR TITLE
Add static url

### PR DESCRIPTION
**Pull request by stuft2**

### CODE REVIEW

**Comment by stuft2** [comment]
@joshgubler Not sure how to fix the CI for terraform v0.15 and v1.0. I tried changing the output to sensitive but that didn't work. It was broken before though.

**Review by GaryGSC — COMMENTED** [review]
The approach seems fine to me, but I'm not really sure it's something we _want_.

To me, it seems a static URL implies permanence, which conflicts with some thoughts expressed here in the README:
> temporary bastion

> The bastion is intended to be short lived.

> The bastion is really intended to be ephemeral

@stuft2 - Can you explain the rationale?

@joshgubler - Care to weigh in?

**Comment by stuft2** [comment]
Our team uses this bastion module so often that it's become a burden to tear down the bastion after use. We'd rather have one permanent bastion in each of our accounts than have to spin up a new instance per person per day.

**Comment by yoshutch** [comment]
Wouldn't that in a sense break the idea of trying to keep our data only secure/accessible by the App itself? I mean we had tried to keep hands out of the data as much as possible when switching to AWS, so that an inadvertent change couldn't mess up your data etc. A temporary bastion was like the question "are you sure you need to bypass the security to look inside the database?" so, at least in my mind, the bastion module was meant to be temporary. We didn't want to spin up and keep an EC2 running just to connect to the database for debugging purposes. Wouldn't this cost us a decent amount of money to keep a permanent bastion running instead of only spinning it up when you need it?

With a permanent bastion it feels like we're getting back to the ces-prd database (in a sense) where anyone on the VPN can connect anytime.

**Comment by stuft2** [comment]
Regardless of having a permanent bastion or not, this change allows us to keep the same connection configuration between bastions. Without this change, I'd be forced to update my datagrip configuration with the new public ip every time I destroy and redeploy a bastion instance. We'd have more incentive to destroy our bastion instances if we didn't have to update our config each day.

As far as a permanent bastion is concerned for the ces accounts, we have too many developers spending a lot of time troubleshooting bastion -> RDS connections and it's slowing us down. Having one, even if we destroy and rebuild it regularly, greatly simplifies the troubleshooting process.

**Comment by joshgubler** [comment]
I'm ok with CES accounts having a long-lived bastion. They don't have a VPN connection like the BYU accounts, so it really is important for developer convenience. And I don't think we're recreating the problems we have with CESPRD. We aren't creating a central DB that every application will access.

**Comment by joshgubler** [comment]
Rather than thinking of this as a "static URL", I think of it as giving the bastion a "friendly hostname".

**Comment by joshgubler** [comment]
> @joshgubler Not sure how to fix the CI for terraform v0.15 and v1.0. I tried changing the output to sensitive but that didn't work. It was broken before though.

Odd. I don't know why the R53 record name would be considered sensitive.

**Comment by stuft2** [comment]
Additionally, this PR won't change the language in the readme to continue to encourage ephemeral bastions.

> > @joshgubler Not sure how to fix the CI for terraform v0.15 and v1.0. I tried changing the output to sensitive but that didn't work. It was broken before though.
> 
> Odd. I don't know why the R53 record name would be considered sensitive.

Updating the "sensitive" outputs to explicitly mark the output as sensitive breaks v0.14 and below.

```
Error: Output refers to sensitive values

  on ci.tf line 27:
  27: output "ec2_instance" {

Expressions used in outputs can only refer to sensitive values if the
sensitive attribute is true.
```

**Review by joshgubler — DISMISSED** [review]

**Review by yoshutch — DISMISSED** [review]
Would this be a big enough breaking change to warrant a major version upgrade? To `v3.0.0`? especially if you're requiring tf v14?

**Review by GaryGSC — DISMISSED** [review]
Sounds like we've come to the consensus that developer ergonomics outweigh the supposed security risk. I don't have any other concerns.

Thanks for the discussion, everyone!

**Comment by stuft2** [comment]
> Would this be a big enough breaking change to warrant a major version upgrade? To `v3.0.0`? especially if you're requiring tf v14?

It will still work with v0.12 -> v0.14, just not with 0.15 or 1.0 yet. But the current version won't work with 0.15 or 1.0 either 🤷🏻 So nothing breaking, just adding a route53 resource.

**Review by yoshutch — APPROVED** [review]

**Pull request merged**
